# Generated by Django 5.0.6 on 2024-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_alter_gameshop_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameshop',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
